import OpenAI from 'openai';

import { Checklist, ToolName } from '../types/index.js';

import { productionLaunchSystemPrompt } from './prompts.js';

const knownTools: readonly ToolName[] = [
  'analyze_logs',
  'backup',
  'check_containers',
  'check_cpu',
  'check_disk',
  'check_docker',
  'check_health',
  'check_https',
  'check_memory',
  'check_ssl',
  'deploy',
  'fetch_logs',
  'generate_report',
  'restart_service',
  'rollback'
];

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

const isToolName = (value: unknown): value is ToolName =>
  typeof value === 'string' && knownTools.includes(value as ToolName);

export class ProductionLaunchAgent {
  private readonly openai: OpenAI | null;

  constructor(apiKey: string | undefined) {
    this.openai = apiKey ? new OpenAI({ apiKey }) : null;
  }

  async plan(userRequest: string, fallback: Checklist): Promise<Checklist> {
    if (!this.openai) {
      return fallback;
    }

    const response = await this.openai.responses.create({
      input: [
        {
          content: productionLaunchSystemPrompt,
          role: 'system'
        },
        {
          content: userRequest,
          role: 'user'
        }
      ],
      model: 'gpt-5-mini'
    });

    const text = response.output_text.trim();
    const parsed: unknown = JSON.parse(text);

    if (!isRecord(parsed) || !Array.isArray(parsed.steps)) {
      return fallback;
    }

    const steps = parsed.steps.filter(isToolName).map((tool, index) => ({
      id: `llm-${index + 1}-${tool}`,
      tool
    }));

    return steps.length > 0
      ? {
          description: 'Plan generated by ProductionLaunchAgent',
          name: 'llm-production-plan',
          steps
        }
      : fallback;
  }
}
