-- Preparation is private and independent of authorization to send.
ALTER TABLE publication_deliveries
  DROP CONSTRAINT publication_deliveries_mode_check,
  ADD CONSTRAINT publication_deliveries_mode_check CHECK (mode IN ('disabled','mock','live')),
  DROP CONSTRAINT publication_deliveries_status_check,
  ADD CONSTRAINT publication_deliveries_status_check CHECK (status IN ('draft','approved','publishing','published','blocked','uncertain','cancelled','rejected')),
  ADD COLUMN auto_managed BOOLEAN NOT NULL DEFAULT FALSE;

-- A combined social approval must not publish a sponsor's website profile.
-- Existing explicit website approvals retain their visibility.
ALTER TABLE fund_contributions
  ADD COLUMN sponsor_site_visibility_held BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE publication_feeds ALTER COLUMN auto_prepare SET DEFAULT TRUE;
UPDATE publication_feeds SET auto_prepare=TRUE, last_prepared_at=NULL;

-- Rejected deliveries deliberately retain the unique reservation on their batch.
-- They cannot be regenerated by the recurring planner.
